### ISSUE TITLE
Bonjour.RegisterService.Dispose hangs

### ISSUE THREAD

**Issue by RobertBieligIBA** [arkane-systems/Arkane.Zeroconf#5]
I was trying to register and then deregister a service, but on de-register the method Dispose hangs and never comes back.
Is there a solution for it?

Analysis:
Problem is, that this.sdRef.Process (); in method ProcessRegister() is blocking, therefore the this.task will never finish. In Dispose this.task?.Wait (); is called which will block the application.

**Comment by STL1811** [comment]
I have the same problem and to fix this issue, you can change RegisterService.cs,
add variable to the class :
private CancellationTokenSource cts = null;

On registerAsync, add cts.Token : 
this.task = Task.Run (() => this.ProcessRegister ()).ContinueWith (_ => this.task = null,cts.Token) ;

On Dispose, call 
 if (cts != null) cts.Cancel();
instead of ; 
this.task?.Wait () ;

**Comment by cerebrate** [comment]
Included in 1.2 release.
